name: "Publish to GitHub Packages"

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: "20.x"
          cache: "pnpm"
          registry-url: "https://npm.pkg.github.com"
          scope: "@${{ github.repository_owner }}"
      - run: pnpm install
      - run: pnpm run build --filter @${{ github.repository_owner }}/ui
      - run: pnpm publish ./packages/ui --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
